### ISSUE TITLE
Unhandled exception after trying to run program

### ISSUE THREAD

**Issue by Meilu** [LogicalFish/SoccerSimulator#1]
Hello,
Am an employee at gamebasics trying to do a review on your assignment.

Followed the steps provided by the readme, trying to run it with 
`python manage.py runserver`

```
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x1058347b8>
Traceback (most recent call last):
  File "/Users/jurgen/Desktop/SoccerSimulator-master/venv/lib/python3.7/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/Users/jurgen/Desktop/SoccerSimulator-master/venv/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "/Users/jurgen/Desktop/SoccerSimulator-master/venv/lib/python3.7/site-packages/django/core/management/base.py", line 379, in check
    include_deployment_checks=include_deployment_checks,
  File "/Users/jurgen/Desktop/SoccerSimulator-master/venv/lib/python3.7/site-packages/django/core/management/base.py", line 366, in _run_checks
    return checks.run_checks(**kwargs)
  File "/Users/jurgen/Desktop/SoccerSimulator-master/venv/lib/python3.7/site-packages/django/core/checks/registry.py", line 71, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/Users/jurgen/Desktop/SoccerSimulator-master/venv/lib/python3.7/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/Users/jurgen/Desktop/SoccerSimulator-master/venv/lib/python3.7/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/Users/jurgen/Desktop/SoccerSimulator-master/venv/lib/python3.7/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/jurgen/Desktop/SoccerSimulator-master/venv/lib/python3.7/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/jurgen/Desktop/SoccerSimulator-master/venv/lib/python3.7/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/jurgen/Desktop/SoccerSimulator-master/venv/lib/python3.7/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Users/jurgen/Desktop/SoccerSimulator-master/venv/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/jurgen/Desktop/SoccerSimulator-master/SoccerSimulator/urls.py", line 18, in <module>
    from matchup import views
  File "/Users/jurgen/Desktop/SoccerSimulator-master/matchup/views.py", line 3, in <module>
    from backend import settings
  File "/Users/jurgen/Desktop/SoccerSimulator-master/backend/settings.py", line 12, in <module>
    import_teams()
  File "/Users/jurgen/Desktop/SoccerSimulator-master/backend/import_team.py", line 15, in import_teams
    book = openpyxl.load_workbook(BASE_DIR + '/' + filename)
  File "/Users/jurgen/Desktop/SoccerSimulator-master/venv/lib/python3.7/site-packages/openpyxl/reader/excel.py", line 311, in load_workbook
    data_only, keep_links)
  File "/Users/jurgen/Desktop/SoccerSimulator-master/venv/lib/python3.7/site-packages/openpyxl/reader/excel.py", line 126, in __init__
    self.archive = _validate_archive(fn)
  File "/Users/jurgen/Desktop/SoccerSimulator-master/venv/lib/python3.7/site-packages/openpyxl/reader/excel.py", line 98, in _validate_archive
    archive = ZipFile(filename, 'r')
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/zipfile.py", line 1222, in __init__
    self._RealGetContents()
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/zipfile.py", line 1289, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

please let me know if i am doing anything wrong or if you manage to fix this.

**Comment by LogicalFish** [comment]
Hey Meilu,

The error seems to come from the OpenPyxl library that is being used. I am currently unable to reproduce the error, but I expect something is wrong with the file in the media folder.
Are you using the file supplied at 
http://www.gamebasics.nl/wp-content/uploads/2019/02/DevMatchData.xlsx
?

**Comment by Meilu** [comment]
Thanks, that information was new to me. My colleague forgot to mention that i think :P I just created an empty xlsx. it's working now.
